### PR TITLE
Make template Jekyll 3.0 compatible

### PR DESCRIPTION
**Pull request by CjS77**
- Changed the perma-link setting to fix site generation
- Changed highlighter to rouge, which required some CSS changes. I think I caught most of the CSS tags to make the two versions similar, but I may have missed one or two.

### CODE REVIEW

**Comment by koppor** [comment]
<s>Using the changes of `_config.yml` only seems to solve the issue. What is the reason for your changes in the `css` files?</s>

**Comment by CjS77** [comment]
As per pr comments,  the new highlighter for jekyll 3 is rouge, which has slightly different css tags

**Comment by basarat** [comment]
Verified that this fixes it for v3.0 http://alm.tools/ :rose:

**Comment by t413** [comment]
Sorry this took so long to merge, thanks for your help 😄

**Pull request merged**
